apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        #        image: nginx:1.14.2
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: index
      volumes:
      - name: index
        configMap:
          name: index-html
